{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div style="background-color:#a9a9a9;  border: 3px groove #a9a9a9; border-radius:5px;">
    <div style="background-color: #000000; height:55px; color:#FFFFFF;">
        <div style="float: left;">
            <img src="http://www.homegrownmusiq.com/assets/images/logo.jpg" style="width:50px; height:50px;" >
        </div>
        <div style="float: left; margin-top:15px; margin-left: 10px; color:#FFFFFF;"><h3 style="color:#FFFFFF;">Welcome To ' . Config::SITE_NAME . '</h3></div>
    </div>
    <div style="padding:12px; font-size:17px;">
        Hello <span class="email-username-font">' .  $this->userName  . '</span>!!!!,<br /><br />

        Thank you for choosing ' . Config::SITE_NAME .  ' as you Extended Virtual Manager!!!<br /><br />

        Our goal is to help you increase productivity via direct communication.<br />

        Whether your goal is to:<br />

        <ul>
            <li>Increase turns on your commerical washers and dryers.</li>
            <li>Communicate to your tenants or customer directly.</li>
            <li>Market directly to existing customers.</li>
            <li>Gain new customers.</li>
            <li>Offer discounts and new incentives.</li>
            <li>Lower overall operation cost.</li>
        </ul>'

        . Config::SITE_NAME . ' has the tools you need to promote your brand, label, swag and musiQ.<br /><br />

        You can now log into ' . Config::SITE_NAME . ' after you have successfully completed the activation process using your:<br /><br />

        Registered email address: ' . $this->userEmail . ' <br />

        And your registered password.<br /><br />

        Please click on the activation link below to finish the registration.<br />

        <a href="http://' . Config::SITE_DOMAIN  . '/memberz/activation?mp=' . $this->userId . '&seq=' . $this->userName . '&ws=' . $this->userEmail . '">
            http://' . Config::SITE_DOMAIN  . '/memberz/activation?mp=' . $this->userId  .
            '&seq=' . $this->userName .
            '&ws=' . $this->userEmail . '
        </a><br />

        Thank you,<br /><br />

        TEAM ' . Config::SITE_NAME . '!!
    </div>
</div>

{% endblock %}