{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class = "main-content-tier1-wrapper" >
    <p>{{ pageContent }} </p >
    <p>{{ param_sum }}</p>
    <p>{{ loopingArrays }}</p>

    <div class="wrapper">
        <nav class="sass-top-nav">
            <div class="sass-logo">
                getMarvelle
            </div>
            <ul class="sass-top-nav-item">
                <li><a href="#">HOME</a></li>
                <li><a href="#">ABOUT</a></li>
                <li><a href="#">CONTACT</a></li>
            </ul>
        </nav>
       <div class="sass-container">
           <div class="sass-content">
               Sed sit amet leo congue, porta dolor sit amet, lobortis mi . Donec at turpis quis nisi ultrices hendrerit .
               Praesent luctus volutpat lacus, nec consectetur odio cursus at . Phasellus pellentesque sagittis est, id laoreet orci posuere a .
               Sed faucibus sem nunc . Aenean dignissim turpis in metus maximus, eu tempus lorem vehicula .
               Vestibulum pulvinar dignissim risus, molestie tincidunt diam venenatis nec . Quisque id convallis lorem, in vulputate neque .
               Ut erat diam, gravida a blandit sed, rutrum quis ex . Quisque nec est risus .
               <a href="#" class="sass-button">Learn more</a>
               <a href="#" class="sass-button medium success">Learn more</a>
               <a href="#" class="sass-button large error">Learn more</a>

           </div>
           <div class="sass-footer">
               <ul class="inline">
                   <li><a href="">List Item 1</a></li>
                   <li><a href="">List Item 2</a></li>
                   <li><a href="">List Item 3</a></li>
               </ul>

           </div>
       </div>
    </div>
</div >
{% endblock %}